In [ ]:
import numpy as np
np.__version__

#### 2.1、理解python中的数据类型

python整型不仅仅是一个整型，底层是用C实现的，它是一个指针，它包含4个部分：
1. 引用计数，帮助python处理内存的分配和回收
2. 变量的类型编码
3. 数据成员的大小
4. 希望python变量表示的实际整型值

所以，相比C语言的整型数据，python语言更灵活，但是它是以牺牲内存为代价的

python列表不仅仅是一个列表，列表包含两个部分，一个部分是指向指针块的指针，指针块中的每个指针执行一个完整的python对象，另一个部分表示列表的长度


In [33]:
L = [1, 2, "hello", False]
[l for l in L]

[1, 2, 'hello', False]

In [34]:
# 创建/初始化数组
print(np.array([1, 2, 3, 4]))
print(np.array([1, 2, 3, 4.]))
print(np.array([1, 2 ,3, 4], dtype='float32'))
print(np.zeros(10, dtype=int))
print(np.ones((3, 4), dtype=int))
print(np.full((3, 4), 3.14))
print(np.arange(0, 20, 2))
print(np.linspace(0, 1, 5))
print(np.random.random((3, 3)))  # 0-1均匀分布的随机数
print(np.random.normal(0, 1, (3, 3)))  # 均值为0 方差为1的正态分布的随机数
print(np.random.randint(0, 10, (3, 3)))  # 0-10的随机整数 可能重复
print(np.eye(3))  # 3x3单位矩阵

[1 2 3 4]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[0 0 0 0 0 0 0 0 0 0]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[0.60016773 0.28757066 0.49540969]
 [0.05051597 0.04201667 0.59195548]
 [0.75042609 0.79821835 0.7770913 ]]
[[ 1.30165422 -2.12965777 -0.63609374]
 [-0.08480255  0.80809937 -0.4753884 ]
 [-0.04616145  0.61332855 -0.52173647]]
[[3 0 5]
 [5 0 7]
 [3 4 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


numpy常见的标准数据类型

1. bool_: False or True
2. int_: int64
3. int8: -127~128
4. int16/int32/int64
5. float16/32/64

#### 2.1、Numpy数组基础